language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
